#!/bin/sh

# It's a script to build all necessary docker images and push them
# to the local repository, so they will be available from the
# production environment.

docker build -t git.heia.kim/heia.kim/frontend/web:latest -f Dockerfile . --no-cache
DOCKER_CLI_EXPERIMENTAL=enabled docker -D push git.bruder.business/heia.kim/frontend/web:latest

docker build -t git.heia.kim/heia.kim/frontend/php:latest -f docker/deploy/php/Dockerfile . --no-cache
DOCKER_CLI_EXPERIMENTAL=enabled docker -D push git.heia.kim/heia.kim/frontend/php:latest
