#!/bin/sh

# Deploy the docker stack in production.

network=deploy-bridge

docker-compose down
docker network rm $network
docker swarm init
docker network create --driver overlay $network
docker stack deploy -c compose.deploy.yml heiakim
