daemon off;
worker_processes  auto;

pid /data/storage/nginx.pid;

events {
    worker_connections  1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  sendfile      on;

  server {
    listen 80;
    server_name 127.0.0.1;

    root /data/public;
    index yield.php;

    #Error pages
    error_page 500 /yield.php?page=404;
    error_page 404 /yield.php?page=404;
    error_page 403 /yield.php?page=404;

    #PHP-FPM Configuration Nginx
    location ~ \.php$ {
      try_files            $uri =404;
      fastcgi_pass         heiakim-frontend-php:9000;
      fastcgi_param        SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_read_timeout 60;
      include              /etc/nginx/fastcgi_params;
    }

    #API
    rewrite ^/(?<model>[a-z]+)/(.*)/(.*)/(.*)/(.*)
      /requests/api/v1/index.php?model=$1&id=$2&model2=$3&id2=$4&id3=$5&$query_string last;

    rewrite ^/(?<model>[a-z]+)/(.*)/(.*)/(.*)
      /requests/api/v1/index.php?model=$1&id=$2&model2=$3&id2=$4&$query_string last;

    rewrite ^/(?<model>[a-z]+)/(.*)/(.*)
      /requests/api/v1/index.php?model=$1&id=$2&model2=$3&$query_string last;

    rewrite ^/(?<model>[a-z]+)/(.*)
      /requests/api/v1/index.php?model=$1&id=$2&$query_string last;

    rewrite ^/(?<model>[a-z]+)
      /requests/api/v1/index.php?model=$1&$query_string last;

    rewrite ^/
      /requests/api/v1/index.php last;
  }
}