#API
rewrite ^/(?<model>[a-z]+)/(.*)/(.*)/(.*)/(.*)
  /requests/api/v1/index.php?model=$1&id=$2&model2=$3&id2=$4&id3=$5&$query_string last;

rewrite ^/(?<model>[a-z]+)/(.*)/(.*)/(.*)
  /requests/api/v1/index.php?model=$1&id=$2&model2=$3&id2=$4&$query_string last;

rewrite ^/(?<model>[a-z]+)/(.*)/(.*)
  /requests/api/v1/index.php?model=$1&id=$2&model2=$3&$query_string last;

rewrite ^/(?<model>[a-z]+)/(.*)
  /requests/api/v1/index.php?model=$1&id=$2&$query_string last;

rewrite ^/(?<model>[a-z]+)
  /requests/api/v1/index.php?model=$1&$query_string last;

rewrite ^/
  /requests/api/v1/index.php last;