CREATE TABLE web_error_logs(
  id INT NOT NULL AUTO_INCREMENT,
  user_id INT NULL,
  area TEXT NULL,
  log_message TEXT NULL,
  log_reference TEXT NULL,
  updated_at TIMESTAMP NULL,
  created_at TIMESTAMP NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;