CREATE TABLE user_name_changes(
  id INT NOT NULL AUTO_INCREMENT,
  user_id INT NULL,
  name TEXT NULL,
  updated_at TIMESTAMP NULL,
  created_at TIMESTAMP NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;