BEGIN;

CREATE TABLE user_audios(
  id INT NOT NULL AUTO_INCREMENT,
  user_id INT NULL,
  set_id INT NULL,
  deleted_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL default CURRENT_TIMESTAMP,
  created_at TIMESTAMP NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE INDEX user_id_index
ON user_audios (user_id);

COMMIT;