BEGIN;

CREATE TABLE artists(
  id INT NOT NULL AUTO_INCREMENT,
  name TEXT NULL,
  updated_at TIMESTAMP NULL,
  created_at TIMESTAMP NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

COMMIT;